axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
  amqp:
    exchange: ${RABBITMQ_EXCHANGE:events}
server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: auction-cmd-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/auctiondb}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:admin123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    
eauction:
  rabbitmq:
    queue: events

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
